### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by Redth** [samskivert/ikvm-monotouch#4]
Hey @samskivert 

I'm wondering if you could give some advice on this project.  I'm currently trying to work with a C# port of ZXing which is quite out of date from the java project.  I'm wondering if it's feasible to try and use ikvm-monotouch to create a monotouch and mono for android friendly version of ZXing binary to use.  

Is ikvm-monotouch complete enough, in your opinion, to give this a try?

**Comment by samskivert** [comment]
Does ZXing use a lot of JDK platform features? If it's just processing QR code images, I would imagine that it is not. However, I don't think you're going to be able to just run the jar file through IKVM and magically have something that works. If ZXing uses APIs that access the camera, those will be different on iOS, and if it manipulates bitmaps, that's going to be Bitmap objects on Android and UIImage objects on Android. So there will be some porting needed.

**Comment by Redth** [comment]
Hey @samskivert 

ZXing doesn't use a lot of JDK platform features.  I should have been more detailed at first, but basically I already have the normal IKVM branch working to create a binary that works on Windows fine.  The ZXing library itself does not deal much with the actual image capture on any specific platforms, and I have code already dealing with that part of it (including platform specific bitmap implementations).  I'm more concerned in the base library.  I guess I'll give it a try and see what happens :)
