### ISSUE TITLE
Using ikvmc

### ISSUE THREAD

**Issue by Redth** [samskivert/ikvm-monotouch#5]
So I've got ikvm-monotouch compiled successfully, no issue there.

Now when I go to run:

```
  mono ikvmc core.jar
```

I get the error:
Error: unable to find assembly 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'
    (a dependency of 'IKVM.OpenJDK.Core, Version=0.46.0.1, Culture=neutral, PublicKeyToken=null')

Now, when I utilize the lib parameter:

```
mono ikvmc.exe -lib:/Library/Frameworks/Mono.framework/Home/lib/mono/2.1 core.jar
```

I get the error:
Error: unable to load assembly '/Library/Frameworks/Mono.framework/Home/lib/mono/2.1/System.dll' as it depends on a higher version of mscorlib than the one currently loaded

I'm not quite sure what libs I should be pointing at now... Any suggestions?

**Comment by samskivert** [comment]
Here's an example of an execution of ikvmc.exe with all the appropriate chicken sacrifice:

```
ikvm-monotouch/bin/ikvmc.exe -nostdlib -target:library -debug -out:mygame.dll
  -r:/Developer/MonoTouch/usr/lib/mono/2.1/mscorlib.dll
  -r:/Developer/MonoTouch/usr/lib/mono/2.1/System.dll
  -r:/Developer/MonoTouch/usr/lib/mono/2.1/System.Core.dll
  -r:/Developer/MonoTouch/usr/lib/mono/2.1/System.Data.dll
  -r:/Developer/MonoTouch/usr/lib/mono/2.1/OpenTK-1.0.dll
  -r:/Developer/MonoTouch/usr/lib/mono/2.1/monotouch.dll
  -r:/Developer/MonoTouch/usr/lib/mono/2.1/Mono.Data.Sqlite.dll
  '-recurse:dll-classes/*.class'
```

That should be all one line, I just wrapped it for clarity here.
